//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonte
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FONTEEntities : DbContext
    {
        public FONTEEntities()
            : base("name=FONTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetDiasFonteAB1_Result> GetDiasFonteAB1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDiasFonteAB1_Result>("GetDiasFonteAB1");
        }
    
        public virtual ObjectResult<GetDiasFonteAB2_Result> GetDiasFonteAB2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDiasFonteAB2_Result>("GetDiasFonteAB2");
        }
    }
}
