//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonte
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FONTEEntitiesHorasASB : DbContext
    {
        public FONTEEntitiesHorasASB()
            : base("name=FONTEEntitiesHorasASB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetHotasFonteASB1_Result> GetHotasFonteASB1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotasFonteASB1_Result>("GetHotasFonteASB1");
        }
    
        public virtual ObjectResult<GetHotasFonteASB2_Result> GetHotasFonteASB2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotasFonteASB2_Result>("GetHotasFonteASB2");
        }
    }
}
